services:
  frontend:
    container_name: nextjs
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - project-network

  backend:
    container_name: laravel
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "81:80"
    volumes:
      - "./backend:/var/www/html"  # This will mount the entire backend directory
      - "./backend/docker/nginx.conf:/etc/nginx/nginx.conf"
      - "./backend/docker/supervisord.conf:/usr/local/etc/supervisord.conf"
      - "./backend/docker/php.ini:/etc/php.ini"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: db
      DB_USERNAME: root
      DB_PASSWORD: root
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    depends_on:
      - db
    networks:
      - project-network

  db:
    container_name: db
    image: mysql:latest
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db:/var/lib/mysql
      - ./backend/docker/my.conf:/etc/my.conf
    networks:
      - project-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      PMA_HOST: db
    networks:
      - project-network 
      
networks:
  project-network:
    driver: bridge

volumes:
  db:
    driver: local